"""baseline schema

Revision ID: c22007620669
Revises:
Create Date: 2026-09-15 20:41:42.343225
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c22007620669'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.String(length=100), nullable=False),
    sa.Column('approval_code', sa.String(length=100), nullable=False),
    sa.Column('approval_title', sa.String(length=255), nullable=False),
    sa.Column('applicant_name', sa.String(length=100), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('task_status', sa.Enum('pending', 'parsing', 'reviewing', 'blocked', 'done', name='task_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('write_status', sa.Enum('not_written', 'writing', 'success', 'failed', name='write_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('blocked_stage', sa.String(length=50), nullable=True),
    sa.Column('blocked_reason', sa.Text(), nullable=True),
    sa.Column('retry_target', sa.String(length=50), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('approval_code', name='uq_approval_tasks_approval_code'),
    sa.UniqueConstraint('instance_id', name='uq_approval_tasks_instance_id')
    )
    op.create_table('review_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_code', sa.String(length=100), nullable=False),
    sa.Column('rule_name', sa.String(length=200), nullable=False),
    sa.Column('risk_level', sa.Enum('low', 'medium', 'high', name='risk_level', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('rule_status', sa.Enum('active', 'inactive', name='review_rule_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('match_mode', sa.Enum('field_missing', 'numeric_threshold', 'keyword', 'presence', 'future_llm', name='review_rule_match_mode', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('match_text', sa.Text(), nullable=False),
    sa.Column('suggestion_text', sa.Text(), nullable=False),
    sa.Column('rule_version', sa.String(length=50), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_code')
    )
    op.create_table('approval_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('external_attachment_id', sa.String(length=100), nullable=False),
    sa.Column('original_file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('is_main_contract', sa.Boolean(), nullable=False),
    sa.Column('download_status', sa.Enum('pending', 'success', 'failed', name='download_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('download_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['approval_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'external_attachment_id', name='uq_approval_attachments_task_external_id')
    )
    op.create_index(op.f('ix_approval_attachments_task_id'), 'approval_attachments', ['task_id'], unique=False)
    op.create_table('task_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('log_level', sa.String(length=20), nullable=False),
    sa.Column('log_type', sa.String(length=50), nullable=False),
    sa.Column('log_content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['approval_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_logs_task_id'), 'task_logs', ['task_id'], unique=False)
    op.create_table('document_read_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attachment_id', sa.Integer(), nullable=False),
    sa.Column('read_method', sa.String(length=50), nullable=False),
    sa.Column('file_sha256', sa.String(length=64), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('blocks_json', sa.JSON(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('requires_ocr', sa.Boolean(), nullable=False),
    sa.Column('read_status', sa.Enum('success', 'ocr_required', 'failed', name='document_read_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('reader_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attachment_id'], ['approval_attachments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_read_snapshots_attachment_id'), 'document_read_snapshots', ['attachment_id'], unique=False)
    op.create_index(op.f('ix_document_read_snapshots_file_sha256'), 'document_read_snapshots', ['file_sha256'], unique=False)
    op.create_table('contract_parses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_read_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('basic_info_json', sa.JSON(), nullable=False),
    sa.Column('clause_info_json', sa.JSON(), nullable=False),
    sa.Column('parse_status', sa.Enum('success', 'partial', 'failed', name='contract_parse_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('parse_error', sa.Text(), nullable=True),
    sa.Column('extractor_name', sa.String(length=100), nullable=False),
    sa.Column('extractor_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_read_snapshot_id'], ['document_read_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_parses_document_read_snapshot_id'), 'contract_parses', ['document_read_snapshot_id'], unique=False)
    op.create_table('review_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_parse_id', sa.Integer(), nullable=False),
    sa.Column('overall_risk_level', sa.Enum('low', 'medium', 'high', name='review_result_risk_level', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('focus_points_json', sa.JSON(), nullable=False),
    sa.Column('comment_text', sa.Text(), nullable=False),
    sa.Column('review_status', sa.Enum('completed', 'partial', 'failed', name='review_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('review_error', sa.Text(), nullable=True),
    sa.Column('review_version', sa.String(length=50), nullable=False),
    sa.Column('rule_set_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('rule_hit_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contract_parse_id'], ['contract_parses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_results_contract_parse_id'), 'review_results', ['contract_parse_id'], unique=False)
    op.create_table('rule_hits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_parse_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('rule_version', sa.String(length=50), nullable=False),
    sa.Column('evidence_text', sa.Text(), nullable=False),
    sa.Column('evidence_position', sa.JSON(), nullable=True),
    sa.Column('evidence_type', sa.Enum('source', 'missing', 'derived', name='rule_hit_evidence_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('actual_value', sa.Text(), nullable=True),
    sa.Column('expected_value', sa.Text(), nullable=True),
    sa.Column('hit_message', sa.Text(), nullable=False),
    sa.Column('hit_status', sa.Enum('hit', name='rule_hit_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contract_parse_id'], ['contract_parses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['review_rules.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_parse_id', 'rule_id', 'rule_version', name='uq_rule_hits_parse_rule_version')
    )
    op.create_index(op.f('ix_rule_hits_contract_parse_id'), 'rule_hits', ['contract_parse_id'], unique=False)
    op.create_index(op.f('ix_rule_hits_rule_id'), 'rule_hits', ['rule_id'], unique=False)
    op.create_table('comment_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('review_result_id', sa.Integer(), nullable=False),
    sa.Column('write_status', sa.Enum('not_written', 'writing', 'success', 'failed', name='comment_log_write_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('write_response_text', sa.Text(), nullable=True),
    sa.Column('external_comment_id', sa.String(length=200), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['review_result_id'], ['review_results.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_id'], ['approval_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_logs_review_result_id'), 'comment_logs', ['review_result_id'], unique=False)
    op.create_index(op.f('ix_comment_logs_task_id'), 'comment_logs', ['task_id'], unique=False)
    op.create_table('review_result_rule_hits',
    sa.Column('review_result_id', sa.Integer(), nullable=False),
    sa.Column('rule_hit_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['review_result_id'], ['review_results.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_hit_id'], ['rule_hits.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('review_result_id', 'rule_hit_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_result_rule_hits')
    op.drop_index(op.f('ix_comment_logs_task_id'), table_name='comment_logs')
    op.drop_index(op.f('ix_comment_logs_review_result_id'), table_name='comment_logs')
    op.drop_table('comment_logs')
    op.drop_index(op.f('ix_rule_hits_rule_id'), table_name='rule_hits')
    op.drop_index(op.f('ix_rule_hits_contract_parse_id'), table_name='rule_hits')
    op.drop_table('rule_hits')
    op.drop_index(op.f('ix_review_results_contract_parse_id'), table_name='review_results')
    op.drop_table('review_results')
    op.drop_index(op.f('ix_contract_parses_document_read_snapshot_id'), table_name='contract_parses')
    op.drop_table('contract_parses')
    op.drop_index(op.f('ix_document_read_snapshots_file_sha256'), table_name='document_read_snapshots')
    op.drop_index(op.f('ix_document_read_snapshots_attachment_id'), table_name='document_read_snapshots')
    op.drop_table('document_read_snapshots')
    op.drop_index(op.f('ix_task_logs_task_id'), table_name='task_logs')
    op.drop_table('task_logs')
    op.drop_index(op.f('ix_approval_attachments_task_id'), table_name='approval_attachments')
    op.drop_table('approval_attachments')
    op.drop_table('review_rules')
    op.drop_table('approval_tasks')
    # ### end Alembic commands ###
